from __future__ import annotations

MODULE_ANNONCE = "ANNONCE"
MODULE_BILAN = "BILAN"
ALLOWED_MODULES = {MODULE_ANNONCE, MODULE_BILAN}

MODE_ADD_ONLY = "ADD_ONLY"
MODE_FILL_EMPTY = "FILL_EMPTY"
MODE_REPLACE_SELECTED = "REPLACE_SELECTED"
ALLOWED_MODES = {MODE_ADD_ONLY, MODE_FILL_EMPTY, MODE_REPLACE_SELECTED}

STATUS_PREVIEW = "PREVIEW"
STATUS_PENDING_VALIDATION = "PENDING_VALIDATION"
STATUS_APPLIED = "APPLIED"
STATUS_ROLLED_BACK = "ROLLED_BACK"
STATUS_REJECTED = "REJECTED"
STATUS_FAILED = "FAILED"

ROW_NEW = "NEW"
ROW_COMPLEMENT = "COMPLEMENT"
ROW_IDENTICAL = "IDENTICAL"
ROW_CONFLICT = "CONFLICT"
ROW_INVALID = "INVALID"
ROW_SKIPPED = "SKIPPED"
ROW_APPLIED = "APPLIED"

SUPPORTED_EXTENSIONS = {".xlsx", ".xlsm", ".csv"}
MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024

VOLATILE_SNAPSHOT_KEYS = {
    "created_at",
    "updated_at",
    "heure_saisie_reelle",
}

# Aliases sûrs et connus entre d'anciens classeurs et les codes actuels.
RESTITUTION_CODE_ALIASES = {
    "TRANSFERT": "TRANSFERT_DAR_KHROFA",
    "IRRIGATION_LOUKKOS_PRISE_AGRICOLE": "IRRIGATION_LOUKKOS_PRISE",
    "SIPHON_DIGUE": "SIPHON",
}
